Repository PaddlePaddle/community, pull requests merged in 2022-03, with the labels that each got.

#21 【Hackathon No.3】
  rfcs/rcf_corrcoef/20200310_api_design_for_corrcoef.md
Labels: contributor, status：accepted

#33 【Hackathon No.13】
  rfcs/APIs/20220314_api_design_for_CyclicLR.md
Labels: contributor, status：open review

#23 【Hackathon No.8】
  rfcs/APIs/20220311_api_design_for_nanmean.md
Labels: contributor, status: revision

#45 Revert "【Hackathon No.8】"
  rfcs/APIs/20220311_api_design_for_nanmean.md
Labels: contributor, status: proposed

#46 【Hackathon No.3】
  rfcs/APIs/20200310_api_design_for_corrcoef.md
Labels: contributor, status: proposed

#47 【Hackathon No.8】
  rfcs/APIs/20220311_api_design_for_nanmean.md
Labels: contributor, status: proposed

#48 【Hackathon No.8】rfc文件修改
  rfcs/APIs/20220311_api_design_for_nanmean.md
Labels: contributor, status: proposed

#50 【Hackathon No.23】为 Paddle 新增 Softmax2D 组网API
  rfcs/APIs/20220318_api_design_for_nn_Softmax2D.md
Labels: contributor, status: revision

#44 【Hackathon No.29】add RFC for PixelUnshuffle
  rfcs/APIs/20220317_api_design_for_PxielUnshuffle.md
Labels: contributor, status: revision

#53 [Hackathon No.14]
  rfcs/APIs/api_design_for_multilabel_soft_margin_loss.md
Labels: contributor, status: revision

#40 【Hackathon No.24】add RFC for ChannelShuffle
  rfcs/APIs/20220317_api_design_for_ChannelShuffle.md
Labels: contributor, status: revision

#34 【Hackathon No.30】
  rfcs/APIs/api_design_for_tripletmargindistanceloss.md
Labels: contributor, status: revision

#31 [Hackthon No.26]
  rfcs/APIs/20220313_api_design_for_tripletmarginloss.md
Labels: contributor, status: revision

#52 【Hackathon No.17】
  rfcs/APIs/20220319_api_design_for_CosineEmbeddingLoss.md
Labels: contributor, status: revision

#60 【Hackathon No.29】 新增 PixelUnshuffle API 设计文档
  rfcs/APIs/20220317_api_design_for_PixelUnshuffle.md
Labels: contributor, status: open review

#51 【Hackathon No.27】为 Paddle 新增 frac 数学计算API
  rfcs/APIs/20220319_api_design_for_frac.md
Labels: contributor, status: revision

#66 Hackathon No.5
  rfcs/APIs/20220323_api_design_for_tril_indices.md
Labels: contributor, status: open review

#54 【Hackathon No.70】
  rfcs/Docs/20220320_docs_eval_docs.md
Labels: contributor, status: revision

#57 【Hackathon No.18】 新增 heaviside API 设计文档
  rfcs/APIs/20220321_api_design_for_heaviside.md
Labels: contributor, status: open review

#69 Fix typo in api_design_template.md
  rfcs/APIs/api_design_template.md
Labels: contributor, status: proposed

#37 【Hackathon No.7】add rfc: api design for cdist
  rfcs/APIs/20220316_api_design_for_cdist.md
Labels: contributor, status: open review

#29 【Hackathon No.12】为paddle新增OneCycleLR优化调度器
  rfcs/APIs/20210312_api_design_for_one_cycle_lr.md
Labels: contributor, status: revision

#63 【Hackathon No.74】为 PaddleScience 增加中文文档
  rfcs/Science/20220320_docs_design_for_paddlescience.md
Labels: contributor, status: open review

#72 【Hackathon No.93】在PaddleFSL将模型库中的MAML和ANIL转为优化算法api
  rfcs/APIs/20220328_design_for_fsl_metaopt.md
Labels: contributor, status: proposed

#81 【Hackathon No.88】实现 Taichi 和 PaddlePaddle 之间的无拷贝交互
  rfcs/Taichi/Copy-free interaction between Taichi and PaddlePaddle.md
Labels: contributor, status: proposed

#74 【Hackathon No.56】
  rfcs/APIs/20220329_api_design_for_sparse_add.md
Labels: contributor, status: open review

#75 【Hackathon No.57】
  rfcs/APIs/20020329_api_design_for_sparse_subtract.md
Labels: contributor, status: open review

#76 【Hackathon No.58】
  rfcs/APIs/20220329_api_design_for_sparse_multiply.md
Labels: contributor, status: open review

#77 【Hackathon No.59】
  rfcs/APIs/20220329_api_design_for_sparse_divide.md
Labels: contributor, status: open review
