Repository PaddlePaddle/community, pull requests merged in 2022-10, with the labels that each got.

#287 [CodeStyle] add `introducing flake8` RFC
  pfcc/call-for-contributions/README.md
  pfcc/call-for-contributions/code_style_flake8.md
  rfcs/CodeStyle/20220927_introducing_flake8.md
Labels: contributor, status: proposed

#291 [Paddle Hackathon No.11]
  rfcs/APIs/20220707_api_design_for_multi_margin_loss.md
Labels: contributor, status: proposed

#298 add cdf function for gumbel
  rfcs/APIs/20220908_api_design_for_gumbel.md
Labels: contributor, status: proposed

#301 Update 20220905_api_design_for_sparse_reshape.md to make the RFC agree with the actual implementation
  rfcs/APIs/20220905_api_design_for_sparse_reshape.md
Labels: contributor, status: proposed

#305 [CodeStyle] update `introducing flake8` RFC
  pfcc/call-for-contributions/code_style_flake8.md
  pfcc/call-for-contributions/legacy_python2.md
  rfcs/CodeStyle/20220927_introducing_flake8.md
Labels: contributor, status: proposed

#312 update 2022-10-20-meeting-agenda.md
  pfcc/meetings/2022/2022-10-20-meeting-agenda.md
Labels: contributor, status: proposed

#262 【PaddlePaddle Hackathon 3】No.57 PaddelScience 支持对外部导入的几何文件进行法向外扩采样
  rfcs/Science/20220912_stl_inflation.md
Labels: contributor

#255 No.61：为 PaddleScience 2D 非定常圆柱绕流案例调优精度
  rfcs/Science/20220912_sicience_61.md
Labels: contributor

#122 【Hackathon No.11】add RFC for index_fill
  rfcs/APIs/20220429_api_design_for_index_fill.md
Labels: contributor, status: revision

#306 feat: 完善 No.89：开源社区对比研究
  reports/insight/insight/89_源光闪烁.ipynb
  reports/insight/insight/89_源光闪烁.pdf
Labels: contributor, status: proposed

#313 docker api update
  rfcs/Installation/20221009_docker_api_update.md
Labels: contributor, status: proposed
