Repository PaddlePaddle/community, pull requests merged in 2022-07, with the labels that each got.

#181 add 2022-07-07 meeting minutes
  pfcc/2022-07-07-meeting-agenda.md
  pfcc/2022-07-07-meeting-minutes.md
Labels: contributor, status: proposed

#172 【Hackathon No.14】为 Paddle 新增 remainder_
  rfcs/APIs/20220708_api_design_for_remainder_.md
Labels: contributor

#161 Modify Paddle Hackathon No.21 RFC
  rfcs/APIs/20220416_api_design_for_SotftMarginLoss.md
Labels: contributor, status: proposed

#135 Add RFC for batchnorm1d optim
  rfcs/APIs/20220522_api_optim_batchnorm1d.md
  rfcs/APIs/image/bn-opt.png
Labels: contributor, status: open review

#175 【Hackathon No.63】为 PaddleScience 2D 非定常圆柱绕流案例进行训练过程动力学行为进行分析
  rfcs/Science/20220706_analysis_of_2d_cylinder_flow_for_paddlescience.md
Labels: contributor, status: proposed

#164 【Hackathon No.17】为 Paddle 新增 sgn
  rfcs/APIs/20220705_api_design_for_sgn.md
Labels: contributor, status: proposed

#176 【Hackathon No.5】为 Paddle 新增 bucketize
  rfcs/APIs/20220708_api_design_for_bucketize.md
Labels: contributor, status: proposed

#173 【Hackathon No.6】为 Paddle 新增 trapezoid
  rfcs/APIs/20220708_api_design_for_trapezoid.md
Labels: contributor

#182 【Hackathon No.77】为神经网络编译器 CINN 增加 squeeze 算子
  rfcs/CINN/APIs/20220711_api_design_for_squeeze.md
Labels: contributor, status: proposed

#178 【Hackathon No.66】为 PaddleScience 增加损失函数权重自适应功能
  rfcs/Science/20220710_api_design_for_GradNorm.md
Labels: contributor, status: proposed

#166 【Hackathon No.20】为 Paddle 新增 vsplit
  rfcs/APIs/20220706_api_design_for_vsplit.md
Labels: contributor

#186 【Hackathon No.16】add RFC for take API
  rfcs/APIs/20220714_api_design_for_take.md
Labels: contributor, status: proposed
