Repository PaddlePaddle/community, pull requests merged in 2022-04, with the labels that each got.

#39 【Hackathon No.20】
  rfcs/APIs/20220316_api_design_for_cummax.md
Labels: contributor, status: revision

#55 【Hackathon No.25】为paddle新增 nanquantile
  rfcs/APIs/20220420_api_design_for_nanquantile.md
Labels: contributor, status: revision

#90 【Hackathon No.60】RFC for sparse sqrt
  rfcs/APIs/20220331_api_design_for_paddle_sparse_sqrt.md
Labels: contributor, status: proposed

#62 【Hackathon No.10】为 Paddle 新增 AdaptiveLogSoftmaxWithLoss API
  rfcs/APIs/20200322_api_design_for_AdaptiveLogSoftmaxWithLoss.md
Labels: contributor, status: open review

#67 【Hackathon No.62】Added RFC for Task 62 of PaddlePaddle Hackathon 2
  rfcs/Lite/rfcs_62.md
Labels: contributor, status: open review

#61 【Hackathon No.95】
  rfcs/Julia/20220322_ChainRules_NeuralPDE.md
Labels: contributor, status: open review

#82 【Hackathon No.28】RFC For logcumsumexp
  rfcs/APIs/20220330_api_design_for_logcumsumexp.md
Labels: contributor, status: open review

#95 fix typo and design of sparse rfc
  rfcs/APIs/20020329_api_design_for_sparse_subtract.md
  rfcs/APIs/20220329_api_design_for_sparse_add.md
  rfcs/APIs/20220329_api_design_for_sparse_divide.md
  rfcs/APIs/20220329_api_design_for_sparse_multiply.md
Labels: contributor, status: proposed

#85 【Hackathon No.113】RFC
  rfcs/APIs/20220330_api_eval_for_fleet
Labels: contributor, status: open review

#79 【Hackathon No.64】Added RFC for Paddle-Lite-Demo mobilenet_v3 Demo
  rfcs/Lite/rfc_64.md
Labels: contributor, status: open review

#68 【Hackathon No.19】Add ASGD RFC
  rfcs/APIs/20220327_api_design_for_ASGD.md
Labels: contributor, status: open review

#71 【Hackathon No.16】add RFC for RRelu
  rfcs/APIs/20220329_api_design_for_RRelu.md
Labels: contributor, status: open review

#78 【Hackathon No.63】add RFC for Paddle-Lite-Demo Yolov5
  rfcs/Lite/20220329_yolov5_android.md
Labels: contributor, status: open review

#89 【Hackathon No.15】add RFC for Nanmedian
  rfcs/APIs/20220331_api_design_for_nanmedian.md
Labels: contributor, status: open review

#83 【Hackathon No.1&No.2】为 Paddle 新增 finfo API和iinfo API
  rfcs/APIs/20220330_api_design_for_finfo.md
  rfcs/APIs/20220330_api_design_for_iinfo.md
Labels: contributor, status: revision

#113 【Hackathon No.111】RFC提交
  rfcs/Docs/【Hackathon No.111】RFC.md
Labels: contributor, status: proposed

#93 【Hackathon No.6】RFC for nan_to_num
  rfcs/APIs/20220331_api_design_for_nan_to_num.md
Labels: contributor, status: revision

#115 Add another issue about panel
  pfcc/2022-04-14-meeting-minutes.md
Labels: contributor, status: proposed

#86 【Hackathon No.65】Added RFC for Web Model Converter
  rfcs/Lite/20200330_api_design_for_web_model_converter.md
Labels: contributor, status: revision

#118 Create CHARTER.md
  ppsigs/ppsig-science/CHARTER.md
Labels: contributor, status: proposed

#119 update the goal and file name
  ppsigs/ppsig-science/readme.md
Labels: contributor, status: proposed

#24 【Hackathon No.94】
  rfcs/DeepXDE/20220310_DeepXDE_design_for_paddle.md
Labels: contributor, status: revision

#80 【Hackathon No.76】基于pointer_summarizer完成中文文本摘要任务
  rfcs/APIs/20220330_api_design_for_pointer_summarizer.md
Labels: contributor, status: open review
