Repository PaddlePaddle/community, pull requests merged in 2022-05, with the labels that each got.

#123 【Hackathon No.56 57 58 59】Fix sparse elementwise api RFCs
  rfcs/APIs/20020329_api_design_for_sparse_subtract.md
  rfcs/APIs/20220329_api_design_for_sparse_add.md
  rfcs/APIs/20220329_api_design_for_sparse_divide.md
  rfcs/APIs/20220329_api_design_for_sparse_multiply.md
Labels: contributor, status: proposed

#88 【Hackathon No.69】eval_paddle
  rfcs/paddle_eval/20200331_eval_docs.md
Labels: contributor, status: revision

#58 【Hackathon No.71】为 PaddleScience 新增支持随机/Quasi采样法
  rfcs/Science/20220322_Science_design_for_sample.md
Labels: contributor, status: open review

#131 Update 20220330_api_design_for_logcumsumexp.md
  rfcs/APIs/20220330_api_design_for_logcumsumexp.md
Labels: contributor, status: proposed

#132 更新API OneCycleLR设计文档
  rfcs/APIs/20210312_api_design_for_one_cycle_lr.md
Labels: contributor, status: proposed

#114 【Hackathon No.21】
  rfcs/APIs/20220416_api_design_for_SotftMarginLoss.md
Labels: contributor, status: open review

#133 [feature] add a readme.md for ppsig-model-ocr
  ppsigs/ppsig-models-ocr/CHARTER.md
Labels: contributor, status: proposed

#134 Fix typos.
  rfcs/APIs/20220330_api_design_for_finfo.md
  rfcs/APIs/20220330_api_design_for_iinfo.md
  rfcs/APIs/20220331_api_design_for_nanmedian.md
Labels: contributor, status: proposed

#137 【Hackathon No.16】update RFC for RRelu
  rfcs/APIs/20220329_api_design_for_RRelu.md
Labels: contributor, status: proposed

#136 Modify the TripletMarginWithDistanceLoss RFC
  rfcs/APIs/api_design_for_tripletmargindistanceloss.md
Labels: contributor, status: proposed

#140 Update 2022-05-26-meeting-agenda.md
  pfcc/2022-05-26-meeting-agenda.md
Labels: contributor, status: proposed

#144 【Hackathon No.17】RFC
  rfcs/APIs/20220319_api_design_for_CosineEmbeddingLoss.md
Labels: contributor, status: proposed

#145 更新API CyclicLR设计文档
  rfcs/APIs/20220314_api_design_for_CyclicLR.md
Labels: contributor, status: proposed
