Repository PaddlePaddle/community, pull requests merged in 2023-03, with the labels that each got.

#386 【Hackathon 4 No.23】为 paddle 新增 vander API
  rfcs/APIs/20230227_api_design_for_vander.md
Labels: contributor, status: proposed

#393 Add 2023.03.02 pfcc meeting agenda.
  pfcc/meetings/2023/2023-03-02-meeting-agenda.md
Labels: contributor, status: proposed

#394 [Hackathon 4 No.216 & No.217] add paddleclas_deploy_for_arm.md rfc file
  rfcs/AVH/20230228_paddleclas_deploy_for_arm.md
Labels: contributor, status: proposed

#396 add 20230228_ppocr_cls_deploy_for_arm
  rfcs/AVH/20230222_ppocr_det_deploy_for_arm.md
  rfcs/AVH/20230228_ppocr_cls_deploy_for_arm.md
Labels: contributor, status: proposed

#406 【PaddlePaddle Hackathon 第四期】No.1：为 Paddle 新增 finfo API update
  rfcs/APIs/20220330_api_design_for_finfo.md
Labels: contributor, status: proposed

#384 【Hackathon 4th No.83】为神经网络编译器 CINN 增加 resize 算子
  rfcs/CINN/APIs/20230226_cinn_api_design_resize.md
Labels: contributor, status: proposed

#395 【Hackathon 4 No.16】为 Paddle 新增 PoissonNLLLoss API
  rfcs/APIs/20230301_api_design_for_poissonnllloss.md
Labels: contributor, status: proposed

#405 【Hackathon 4 No.2】为 Paddle 新增 cdist API
  rfcs/APIs/20220316_api_design_for_cdist.md
Labels: contributor, status: proposed

#380 【Hackathon 4 No.81】为神经网络编译器 CINN 增加 bitcast_convert 算子
  rfcs/CINN/APIs/20230221_cinn_api_design_ bitcast_convert.md
Labels: contributor, status: proposed

#407 【PaddlePaddle Hackathon 第四期】No.6：为 Paddle 新增 ldexp API
  rfcs/APIs/20230222_api_design_for_ldexp.md
Labels: contributor, status: proposed

#409 【Hackathon Hackathon No.89】清理动态 import语句，解决circle import 问题
  rfcs/Others/20230304_design_for_remove_circle_import.md
Labels: contributor, status: proposed

#434 add 2023-03-02-meeting-minutes
  pfcc/meetings/2023/2023-03-02-meeting-minutes.md
Labels: contributor, status: proposed

#446 【Hackathon 4th No.15】Add GaussianNLLLoss rfc file.
  rfcs/APIs/20230222_api_design_for_gaussiannllloss.md
Labels: contributor, status: proposed

#402 【PaddlePaddle Hackathon 4 No.230】为TVM 添加tile、mish、stack、unstack、silu、softshrink、where算子支持
  rfcs/TVM/20230302_add_tvm_op_for_paddle_frontend_0.md
Labels: contributor, status: proposed

#404 【PaddlePaddle Hackathon 4 No.229】为TVM 添加dist、take_alone_axis、eye、index_select、thresholded_relu算子支持
  rfcs/TVM/20230302_add_tvm_op_for_paddle_frontend_1.md
Labels: contributor, status: proposed

#382 【Hackathon + No.29】为 Paddle 新增 paddle.sparse.slice 稀疏 API
  rfcs/APIs/20230225_api_design_for_sparse_slice.md
Labels: contributor, status: proposed

#400 【Hackathon4 No.186】 Add "Deploy PaddleDetection Models with Go" RFC
  rfcs/FastDeploy/20230301_deploy_PaddleDetection_by_Go.md
Labels: contributor, status: not progressed

#410 【Hackathon 4th No.180】在FastDeploy中集成集成地平线推理引擎
  rfcs/FastDeploy/20230303_horizon_for_FastDeploy.md
Labels: contributor, status: proposed

#415 【Hackathon 4th No.24】为 Paddle 新增 paddle.sparse.is_nan 稀疏 API
  rfcs/APIs/20230305_api_design_for_paddle_sparse_isnan.md
Labels: contributor

#449 [pfcc] add pfcc regular meeting
  pfcc/meetings/2023/2023-03-16-meeting-agenda.md
Labels: contributor, status: proposed

#408 【Hackathon 4th No.228】为Paddle框架新增TVM算子：grid-sample/gaussian_random/flip/roi_align/fill_zeros_like/unique
  rfcs/TVM/20230303_paddle2tvm_design_228.md
Labels: contributor, status: proposed

#416 【Hackathon 220】add 20230306_pptinypose_deploy_for_arm.md
  rfcs/AVH/20230306_pptinypose_deploy_for_arm.md
Labels: contributor, status: proposed

#451 【Hackathon 4th No.15】Modify GaussianNLLLoss rfc file.
  rfcs/APIs/20230222_api_design_for_gaussiannllloss.md
Labels: contributor, status: proposed

#452 【Hackathon4 No.40】为 Paddle 优化 kthvalue op 在 GPU 上的计算性能
  rfcs/OPs-Perf/20230312_kthvalue_op_optimization.md
Labels: contributor, status: proposed

#463 Change API poisson_nll_loss parameter name from `eps` to `epsilon`
  rfcs/APIs/20230301_api_design_for_poissonnllloss.md
Labels: contributor, status: proposed

#414 【Hackathon No.32】为 Paddle 优化 expand_as 前向&反向 op 在 GPU 上的计算性能
  rfcs/OPs-Perf/20230305_expand_as_optimization.md
Labels: contributor, status: proposed

#460 【Hackathon 4th No.7】为 Paddle 新增 Unflatten API
  rfcs/APIs/20230314_api_design_for_unflatten.md
Labels: contributor, status: proposed

#453 【Hackathon 4th No.13】为 Paddle 新增 Bernoulli API
  rfcs/APIs/20230313_api_design_for_distribution_bernoulli.md
Labels: contributor, status: proposed

#371 98号任务RFC
  rfcs/升级paddlenlp.transformers内的模型结构并且增加基础单测.md
Labels: contributor, status: proposed

#437 【Hackathon No.101】 升级paddlenlp.transformers内的模型结构并且增加基础单测
  rfcs/20230307_paddlenlp_transformers_configuration.md
Labels: contributor, status: proposed

#471 【Hackathon 4th No.20】Added paddle.i0 / paddle.i0e API rfc doc
  rfcs/APIs/20230221_api_design_for_polor.md
  rfcs/APIs/20230318_api_design_for_i0&i0e.md
Labels: contributor

#474 【Hackathon No.9】为 Paddle 新增 pca_lowrank API
  .pre-commit-config.yaml
  rfcs/APIs/20230321_api_design_for_pca_lowrank.md
Labels: contributor

#472 【PaddlePaddle Hackathon 第四期】No.19：为 Paddle 新增 polygamma API
  rfcs/APIs/20230324_api_design_for_polygamma.md
Labels: contributor

#477 【Hackathon No. 91】add: rfcs for tensorhook
  rfcs/Others/TensorHook_dy2static.md
Labels: contributor, status: proposed

#488 【Hackathon 4th No.20】Updated paddle.i0 / paddle.i0e API rfc doc
  rfcs/APIs/20230318_api_design_for_i0&i0e.md
Labels: contributor, status: proposed

#489 Update i1/i1e API rfc doc
  rfcs/APIs/20230326_api_design_for_i1&i1e.md
Labels: contributor, status: proposed

#484 Fix inconsistency between poisson_nll_loss rfc and implementation
  rfcs/APIs/20230301_api_design_for_poissonnllloss.md
Labels: contributor, status: proposed
